### ISSUE TITLE
Formtastic::UnknownInputError

### ISSUE THREAD

**Issue by ghost** [mjbellantoni/formtastic-bootstrap#17]
Using Formtastic-bootstrap: 1.1.2
Using Formtastic 2.0.2

I'm getting an issue when using formtastic-bootstrap with rails3-jquery-autocomplete.  For reference: https://github.com/crowdint/rails3-jquery-autocomplete/issues/128.  The issue occurs when using:
`f.input :something :as => :autocomplete, :url => "some path"`

Removing formastic.rb from config/initializers allows the page to render correctly(without the gem's styling) and the autocomplete functionality to work.  Any ideas?

Trace
`formtastic (2.0.2) lib/formtastic/helpers/input_helper.rb:353:in `rescue in input_class'
formtastic (2.0.2) lib/formtastic/helpers/input_helper.rb:345:in `input_class'
formtastic (2.0.2) lib/formtastic/helpers/input_helper.rb:265:in `input'`

**Comment by sodabrew** [comment]
Note to self, follow up on whether this still makes sense:
https://github.com/crowdint/rails3-jquery-autocomplete/issues/128#issuecomment-10545152
